services:
  web:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    volumes:
      # -----------------------------------------------------------
      - laravel-storage-production:/var/www/storage
      - laravel-public-assets:/var/www/public/build
    networks:
      - laravel-production
    ports:
      # -----------------------------------------------------------
      - "${NGINX_PORT:-8090}:80"
    depends_on:
      - php-fpm
    restart: unless-stopped

  db:
    image: mariadb:10.5.7
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=unitech_db
    restart: unless-stopped
    networks:
      - laravel-production
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-papp"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  htmltoimage:
    image: "monkeyphysics/html-to-image"
    ports:
      - "3033:3033"
    restart: unless-stopped
    networks:
      - laravel-production

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    volumes:
      - laravel-public-assets:/var/www/public/build
      - laravel-storage-production:/var/www/storage
    env_file:
      - .env
    networks:
      - laravel-production
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mongodb-data:
  laravel-storage-production:
  laravel-public-assets:

networks:
  default:
    name: backend-network
  laravel-production:
