services:
  db:
    image: mariadb:10.5.7
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=unitech_db
    restart: unless-stopped
    networks:
      - laravel-production
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-papp"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s
  php-fpm:
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: app
    networks:
      - laravel-production
    depends_on:
      - db
